version: "3"


services:

  webapp:
    build: webapp
    networks:
      - homepage_network

  api:
    build: api
    networks:
      - homepage_network
    env_file:
      - api/.env

  proxy:
    build: proxy
    ports:
      - 80:9000
      - 8080:8080
    networks:
      - homepage_network
    depends_on:
      - webapp
      - api

  jenkins:
    build: CI
    container_name: jenkins
    privileged: true
    restart: always
    networks:
      - homepage_network
    volumes:
    - ./jenkins_home:/var/jenkins_home
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/local/bin/docker:/usr/bin/docker

  registry:
    image: registry
    container_name: registry
    networks:
      - homepage_network
    restart: always
    ports:
      - 5000:5000
  mongo:
    image: mongo:latest
    command: mongod


networks:
  homepage_network:
    driver: bridge