export const authTypes = {
    LOG_IN: "LOG_IN",
    LOG_IN_FULFILLED: "LOG_IN_FULFILLED",
    LOG_IN_REJECTED: "LOG_IN_REJECTED",

    REGISTER: "REGISTER",
    REGISTER_FULFILLED: "REGISTER_FULFILLED",
    REGISTER_REJECTED: "REGISTER_REJECTED",

    AUTHENTICATE: "AUTHENTICATE",
    AUTHENTICATE_FULFILLED: "AUTHENTICATE_FULFILLED",
    AUTHENTICATE_REJECTED: "AUTHENTICATE_REJECTED",
}

export const appbarTypes = {
    SET_APPBAR_TITLE: "SET_TITLE",
    SET_APPBAR_LEFT: "SET_APPBAR_LEFT",
    SET_APPBAR_RIGHT: "SET_APPBAR_RIGHT",
    SET_APPBAR_CLASSES: "SET_APPBAR_CLASSES",
    DISABLE: "DISABLE",
}

export const propertyTypeTypes = {
    GET_PROPERTY_TYPES: "GET_PROPERTY_TYPES",
    GET_PROPERTY_TYPES_FULFILLED: "GET_PROPERTY_TYPES_FULFILLED",
    GET_PROPERTY_TYPES_REJECTED: "GET_PROPERTY_TYPES_REJECTED",

    GET_PROPERTY_TYPE: "GET_PROPERTY_TYPE",
    GET_PROPERTY_TYPE_FULFILLED: "GET_PROPERTY_TYPE_FULFILLED",
    GET_PROPERTY_TYPE_REJECTED: "GET_PROPERTY_TYPE_REJECTED",

    ADD_PROPERTY_TYPE: "ADD_PROPERTY_TYPE",
    ADD_PROPERTY_TYPE_FULFILLED: "ADD_PROPERTY_TYPE_FULFILLED",
    ADD_PROPERTY_TYPE_REJECTED: "ADD_PROPERTY_TYPE_REJECTED",

    DELETE_PROPERTY_TYPE: "DELETE_PROPERTY_TYPE",
    DELETE_PROPERTY_TYPE_FULFILLED: "DELETE_PROPERTY_TYPE_FULFILLED",
    DELETE_PROPERTY_TYPE_REJECTED: "DELETE_PROPERTY_TYPE_REJECTED",

    UPDATE_PROPERTY_TYPE: "UPDATE_PROPERTY_TYPE",
    UPDATE_PROPERTY_TYPE_FULFILLED: "UPDATE_PROPERTY_TYPE_FULFILLED",
    UPDATE_PROPERTY_TYPE_REJECTED: "UPDATE_PROPERTY_TYPE_REJECTED",
}

export const propertyTypes = {
    GET_PROPERTIES: "GET_PROPERTIES",
    GET_PROPERTIES_FULFILLED: "GET_PROPERTIES_FULFILLED",
    GET_PROPERTIES_REJECTED: "GET_PROPERTIES_REJECTED",

    GET_PROPERTY: "GET_PROPERTY",
    GET_PROPERTY_FULFILLED: "GET_PROPERTY_FULFILLED",
    GET_PROPERTY_REJECTED: "GET_PROPERTY_REJECTED",

    ADD_PROPERTY: "ADD_PROPERTY",
    ADD_PROPERTY_FULFILLED: "ADD_PROPERTY_FULFILLED",
    ADD_PROPERTY_REJECTED: "ADD_PROPERTY_REJECTED",

    DELETE_PROPERTY: "DELETE_PROPERTY",
    DELETE_PROPERTY_FULFILLED: "DELETE_PROPERTY_FULFILLED",
    DELETE_PROPERTY_REJECTED: "DELETE_PROPERTY_REJECTED",

    UPDATE_PROPERTY: "UPDATE_PROPERTY",
    UPDATE_PROPERTY_FULFILLED: "UPDATE_PROPERTY_FULFILLED",
    UPDATE_PROPERTY_REJECTED: "UPDATE_PROPERTY_REJECTED",
}
