export const authTypes = {
    LOG_IN: "LOG_IN",
    LOG_IN_FULFILLED: "LOG_IN_FULFILLED",
    LOG_IN_REJECTED: "LOG_IN_REJECTED",

    REGISTER: "REGISTER",
    REGISTER_FULFILLED: "REGISTER_FULFILLED",
    REGISTER_REJECTED: "REGISTER_REJECTED",

    AUTHENTICATE: "AUTHENTICATE",
    AUTHENTICATE_FULFILLED: "AUTHENTICATE_FULFILLED",
    AUTHENTICATE_REJECTED: "AUTHENTICATE_REJECTED",
}

export const appbarTypes = {
    SET_APP_BAR_TITLE: "SET_TITLE",
    SET_APP_BAR_LEFT: "SET_APP_BAR_LEFT",
    SET_APP_BAR_RIGHT: "SET_APP_BAR_RIGHT",
    DISABLE: "DISABLE",
}

export const propTypeTypes = {
    GET_PROPTYPES: "GET_PROPTYPES",
    GET_PROPTYPES_FULFILLED: "GET_PROPTYPES_FULFILLED",
    GET_PROPTYPES_REJECTED: "GET_PROPTYPES_REJECTED",

    GET_PROPTYPE: "GET_PROPTYPE",
    GET_PROPTYPE_FULFILLED: "GET_PROPTYPE_FULFILLED",
    GET_PROPTYPE_REJECTED: "GET_PROPTYPE_REJECTED",

    ADD_PROPTYPE: "ADD_PROPTYPE",
    ADD_PROPTYPE_FULFILLED: "ADD_PROPTYPE_FULFILLED",
    ADD_PROPTYPE_REJECTED: "ADD_PROPTYPE_REJECTED",

    DELETE_PROPTYPE: "DELETE_PROPTYPE",
    DELETE_PROPTYPE_FULFILLED: "DELETE_PROPTYPE_FULFILLED",
    DELETE_PROPTYPE_REJECTED: "DELETE_PROPTYPE_REJECTED",

    UPDATE_PROPTYPE: "UPDATE_PROPTYPE",
    UPDATE_PROPTYPE_FULFILLED: "UPDATE_PROPTYPE_FULFILLED",
    UPDATE_PROPTYPE_REJECTED: "UPDATE_PROPTYPE_REJECTED",
}
